
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.4.1.0
//   File : serialize_types.cpp
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------

#include "serialize_reflection.h"
#include <bond/core/exception.h>

namespace uti
{
namespace serialize
{
    
    namespace _bond_enumerators
    {
    namespace Enum1
    {
        const
        std::map<std::string, enum Enum1> _name_to_value_Enum1 =
            boost::assign::map_list_of<std::string, enum Enum1>
                ("ONE", ONE)
                ("TWO", TWO)
                ("THREE", THREE)
                ("FOUR", FOUR);

        const
        std::map<enum Enum1, std::string> _value_to_name_Enum1 =
            bond::reverse_map(_name_to_value_Enum1);

        const std::string& ToString(enum Enum1 value)
        {
            std::map<enum Enum1, std::string>::const_iterator it =
                GetValueToNameMap(value).find(value);

            if (GetValueToNameMap(value).end() == it)
                bond::InvalidEnumValueException(value, "Enum1");

            return it->second;
        }

        void FromString(const std::string& name, enum Enum1& value)
        {
            std::map<std::string, enum Enum1>::const_iterator it =
                _name_to_value_Enum1.find(name);

            if (_name_to_value_Enum1.end() == it)
                bond::InvalidEnumValueException(name.c_str(), "Enum1");

            value = it->second;
        }

    } // namespace Enum1
    } // namespace _bond_enumerators

    
    const bond::Metadata ints::Schema::metadata
        = ints::Schema::GetMetadata();
    
    const bond::Metadata ints::Schema::s_id_metadata
        = bond::reflection::MetadataInit("id");
    
    const bond::Metadata ints::Schema::s_int1_metadata
        = bond::reflection::MetadataInit("int1");
    
    const bond::Metadata ints::Schema::s_int2_metadata
        = bond::reflection::MetadataInit("int2");
    
    const bond::Metadata ints::Schema::s_int3_metadata
        = bond::reflection::MetadataInit("int3");
    
    const bond::Metadata ints::Schema::s_int4_metadata
        = bond::reflection::MetadataInit("int4");

    
    const bond::Metadata mixed::Schema::metadata
        = mixed::Schema::GetMetadata();
    
    const bond::Metadata mixed::Schema::s_id_metadata
        = bond::reflection::MetadataInit("id");
    
    const bond::Metadata mixed::Schema::s_int1_metadata
        = bond::reflection::MetadataInit("int1");
    
    const bond::Metadata mixed::Schema::s_int2_metadata
        = bond::reflection::MetadataInit("int2");
    
    const bond::Metadata mixed::Schema::s_uint1_metadata
        = bond::reflection::MetadataInit("uint1");
    
    const bond::Metadata mixed::Schema::s_float1_metadata
        = bond::reflection::MetadataInit("float1");
    
    const bond::Metadata mixed::Schema::s_text1_metadata
        = bond::reflection::MetadataInit("text1");
    
    const bond::Metadata mixed::Schema::s_enum1_metadata
        = bond::reflection::MetadataInit(::uti::serialize::_bond_enumerators::Enum1::ONE, "enum1");

    
    const bond::Metadata complex::Schema::metadata
        = complex::Schema::GetMetadata();
    
    const bond::Metadata complex::Schema::s_id_metadata
        = bond::reflection::MetadataInit("id");
    
    const bond::Metadata complex::Schema::s_text1_metadata
        = bond::reflection::MetadataInit("text1");
    
    const bond::Metadata complex::Schema::s_text2_metadata
        = bond::reflection::MetadataInit("text2");
    
    const bond::Metadata complex::Schema::s_text3_metadata
        = bond::reflection::MetadataInit("text3");
    
    const bond::Metadata complex::Schema::s_int1_metadata
        = bond::reflection::MetadataInit("int1");
    
    const bond::Metadata complex::Schema::s_int2_metadata
        = bond::reflection::MetadataInit("int2");
    
    const bond::Metadata complex::Schema::s_int3_metadata
        = bond::reflection::MetadataInit("int3");
    
    const bond::Metadata complex::Schema::s_text4_metadata
        = bond::reflection::MetadataInit("text4");
    
    const bond::Metadata complex::Schema::s_enum1_metadata
        = bond::reflection::MetadataInit(::uti::serialize::_bond_enumerators::Enum1::ONE, "enum1");
    
    const bond::Metadata complex::Schema::s_float1_metadata
        = bond::reflection::MetadataInit("float1");
    
    const bond::Metadata complex::Schema::s_int4_metadata
        = bond::reflection::MetadataInit("int4");
    
    const bond::Metadata complex::Schema::s_uint1_metadata
        = bond::reflection::MetadataInit("uint1");
    
    const bond::Metadata complex::Schema::s_uint2_metadata
        = bond::reflection::MetadataInit("uint2");
    
    const bond::Metadata complex::Schema::s_int5_metadata
        = bond::reflection::MetadataInit("int5");
    
    const bond::Metadata complex::Schema::s_int6_metadata
        = bond::reflection::MetadataInit("int6");
    
    const bond::Metadata complex::Schema::s_float2_metadata
        = bond::reflection::MetadataInit("float2");
    
    const bond::Metadata complex::Schema::s_text5_metadata
        = bond::reflection::MetadataInit("text5");

    
    const bond::Metadata container_vec::Schema::metadata
        = container_vec::Schema::GetMetadata();
    
    const bond::Metadata container_vec::Schema::s_id_metadata
        = bond::reflection::MetadataInit("id");
    
    const bond::Metadata container_vec::Schema::s_int1_metadata
        = bond::reflection::MetadataInit("int1");
    
    const bond::Metadata container_vec::Schema::s_text1_metadata
        = bond::reflection::MetadataInit("text1");
    
    const bond::Metadata container_vec::Schema::s_stringvec_metadata
        = bond::reflection::MetadataInit("stringvec");
    
    const bond::Metadata container_vec::Schema::s_intvec_metadata
        = bond::reflection::MetadataInit("intvec");

    
    const bond::Metadata container_map::Schema::metadata
        = container_map::Schema::GetMetadata();
    
    const bond::Metadata container_map::Schema::s_id_metadata
        = bond::reflection::MetadataInit("id");
    
    const bond::Metadata container_map::Schema::s_int1_metadata
        = bond::reflection::MetadataInit("int1");
    
    const bond::Metadata container_map::Schema::s_text1_metadata
        = bond::reflection::MetadataInit("text1");
    
    const bond::Metadata container_map::Schema::s_map1_metadata
        = bond::reflection::MetadataInit("map1");

    
} // namespace serialize
} // namespace uti
