/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef serialize_CONSTANTS_H
#define serialize_CONSTANTS_H

#include "serialize_types.h"

namespace thrift_serialize {

class serializeConstants {
 public:
  serializeConstants();

};

extern const serializeConstants g_serialize_constants;

} // namespace

#endif
