/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "serialize_constants.h"

namespace thrift_serialize {

const serializeConstants g_serialize_constants;

serializeConstants::serializeConstants() {
}

} // namespace

